export enum LogTypeEvent {
    BeginParty = 'beginParty',
    StartCombat = 'startCombat',
    StartTurn = 'startTurn',
    EndTurn = 'endTurn',
    AttackTo = 'attackTo',
    DefenseFrom = 'defenseFrom',
    EscapeFrom = 'escapeFrom',
    CollectItem = 'collectItem',
    CollectFlag = 'collectFlag',
    CloseDoor = 'closeDoor',
    OpenDoor = 'openDoor',
    QuitGame = 'quitGame',
    EndGame = 'endGame',
    DebugOn = 'debugOn',
    DebugOff = 'debugOff',
    EndFight = 'endFight',
    GiveUp = 'giveUp',
    EndFightWithoutWinner = 'endFightWithoutWinner',
    ComputeDiceAttackBonus = 'computeDiceAttackBonus',
    ComputeDiceDefenseBonus = 'computeDiceDefenseBonus',
    LossTheFlag = 'lossTheFlag',
}
