export enum FightMessageEvent {
    EscapeFailed = 'escapeFailed',
    OpponentEscapeFailed = 'opponentEscapeFailed',
    EscapeSuccessful = 'escapeSuccessful',
    OpponentEscapeSuccessful = 'opponentEscapeSuccessful',
    AttackSuccessful = 'attackSuccessful',
    OpponentAttackSuccessful = 'opponentAttackSuccessful',
    AttackFailed = 'attackFailed',
    OpponentAttackFailed = 'opponentAttackFailed',
    TurnStarted = 'turnStarted',
    OpponentTurnStarted = 'opponentTurnStarted',
    OpponentGaveUp = 'opponentGaveUp',
    YouWon = 'youWon',
    YouLost = 'youLost',
}
